# Generated by Django 5.1 on 2024-08-08 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks_management", "0005_alter_token_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="toDoLists",
            new_name="to_do_lists",
        ),
    ]
