# Generated by Django 4.2.15 on 2024-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_management", "0006_rename_todolists_task_to_do_lists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
    ]
