# Generated by Django 4.2.15 on 2024-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_management", "0007_alter_task_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_priority",
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="low",
                max_length=10,
            ),
        ),
    ]
