# Generated by Django 4.2.15 on 2024-08-14 10:55

import datetime
from django.db import migrations, models
import tasks_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_management", "0011_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default="", verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False, verbose_name="کار تمام شده است؟"),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 8, 14, 10, 55, 54, 555556, tzinfo=datetime.timezone.utc
                ),
                validators=[tasks_management.validators.validate_date],
                verbose_name="ددلاین تسک",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                db_index=True,
                default="Low",
                max_length=6,
                verbose_name="اولویت",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
    ]
