# Generated by Django 4.2.15 on 2024-08-14 15:31

from django.db import migrations, models
import tasks_management.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_management", "0012_alter_task_description_alter_task_done_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                validators=[tasks_management.validators.validate_date]
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
