# Generated by Django 4.2.15 on 2024-08-16 15:36

from django.db import migrations, models
import django.utils.timezone
import tasks_management.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "tasks_management",
            "0014_task_file_alter_task_description_alter_task_done_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[tasks_management.validators.validate_date],
                verbose_name="ددلاین تسک",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
