# Generated by Django 4.2.15 on 2024-08-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_management", "0015_alter_task_due_date_alter_task_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
