# Generated by Django 4.2.15 on 2024-08-16 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_management", "0016_alter_task_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(default=django.utils.timezone.now, upload_to=""),
            preserve_default=False,
        ),
    ]
