# Generated by Django 4.2.15 on 2024-08-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks_management", "0017_alter_task_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(upload_to="media"),
        ),
    ]
