# Generated by Django 5.0.7 on 2024-08-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_to_do_list', '0002_remove_task_todolist_link_task_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='_base',
            new_name='toDoLists',
        ),
    ]
