# Generated by Django 5.0.7 on 2024-08-04 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personal_to_do_list", "0003_rename_todolist_task_todolists"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Link",
            new_name="Token",
        ),
    ]
